# Generated by Django 3.2.4 on 2021-08-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizanswered',
            old_name='answer_name',
            new_name='option_name',
        ),
    ]
