# Generated by Django 3.2.4 on 2021-08-09 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_quizoptions_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='quiz_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quizdetails'),
        ),
    ]
