# Generated by Django 3.2.4 on 2021-07-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_questions_quiz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='quiz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.quizdetails'),
        ),
    ]
