# Generated by Django 3.2.4 on 2021-07-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_questions_quiz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='quiz_id',
            field=models.IntegerField(),
        ),
    ]
