# Generated by Django 3.2.4 on 2021-07-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_questions_quiz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmarks',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quizoptions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quizoptions',
            name='question_id',
            field=models.IntegerField(),
        ),
    ]
