# Generated by Django 3.2.4 on 2021-07-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210719_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswered',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quizanswered',
            name='question_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizmarks',
            name='quiz_id',
            field=models.IntegerField(),
        ),
    ]
