# Generated by Django 3.2.4 on 2021-07-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210719_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_id',
            field=models.IntegerField(null=True),
        ),
    ]
