# Generated by Django 3.2.4 on 2021-07-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_questions_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='quiz_id',
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quizdetails'),
        ),
    ]
