# Generated by Django 3.2.4 on 2021-07-25 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_quizoptions_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizanswered',
            old_name='answer',
            new_name='answer_name',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_id',
        ),
        migrations.AlterField(
            model_name='quizanswered',
            name='question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.questions'),
        ),
    ]
