# Generated by Django 3.2.4 on 2021-07-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210725_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmarks',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
