# Generated by Django 3.2.4 on 2021-07-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_quizmarks_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmarks',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quizdetails'),
        ),
    ]
