# Generated by Django 3.2.4 on 2021-07-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_quizmarks_quiz_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizoptions',
            old_name='question_id',
            new_name='question_fk',
        ),
    ]
