# Generated by Django 3.2.4 on 2021-07-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_question_id_quizoptions_question_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizoptions',
            old_name='question_fk',
            new_name='question_id',
        ),
    ]
