# Generated by Django 3.2.4 on 2021-07-29 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_question_fk_quizoptions_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswered',
            name='quiz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.quizdetails'),
        ),
    ]
