# Generated by Django 3.2.4 on 2021-08-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_quizanswered_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdetails',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
