# Generated by Django 3.2.4 on 2021-08-01 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_quizanswered_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmarks',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.quizdetails'),
        ),
    ]
